#
# See https://docs.microsoft.com/en-us/vsts/pipelines/yaml-schema for details on this file.
#

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build src --configuration $(buildConfiguration)
  displayName: 'dotnet build'

- script: dotnet test src --configuration $(buildConfiguration) --logger trx --collect "Code coverage"
  displayName: 'dotnet test'

- task: PublishTestResults@2
  displayName: 'publish test results'
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: "**/*.trx"

- script: cd && dir && cd installer && cd && dir && make-installer.cmd
  displayName: 'building installer'