using System;
using System.Collections.Generic;
using System.Text;

namespace VLispProfiler
{
    public enum Token
    {
        Illegal,
        EndOfFile,
        Comment,        // Line comment: "; hello"   Inline comment: ;| hello |;

        Identifier,     // defun
        Int,            // 3
        Real,           // 3.14
        String,         // "PI"

        Quote,
        Dot,
        ParenLeft,
        ParenRight
    }

    public sealed class VLispStrings
    {
        public const char Quote = '\'';
        public const char Dot = '.';
        public const char ParenLeft = '(';
        public const char ParenRight = ')';

        public const string Cond = "cond";
        public const string Defun = "defun";
        public const string Lambda = "lambda";

        static VLispStrings()
        {
#region "Set _predefinedIdentifiers"
            _predefinedIdentifiers = new HashSet<string>(StringComparer.InvariantCultureIgnoreCase)
            {
                "+",
                "-",
                "*",
                "/",
                "=",
                "/=",
                "<",
                "<=",
                ">",
                ">=",
                "~",
                "1+",
                "1-",
                "abs",
                "acad_colordlg",
                "acad_helpdlg",
                "acad-pop-dbmod",
                "acad-push-dbmod",
                "acad_strlsort",
                "acad_truecolorcli",
                "acad_truecolordlg",
                "acdimenableupdate",
                "acet-layerp-mode",
                "acet-layerp-mark",
                "acet-laytrans",
                "acet-ms-to-ps",
                "acet-ps-to-ms",
                "action_tile",
                "add_list",
                "alert",
                "alloc",
                "and",
                "angle",
                "angtof",
                "angtos",
                "append",
                "apply",
                "arx",
                "arxload",
                "arxunload",
                "ascii",
                "assoc",
                "atan",
                "atof",
                "atoi",
                "atom",
                "atoms-family",
                "autoarxload",
                "autoload",
                "Boole",
                "boundp",
                "caddr",
                "cadr",
                "car",
                "cdr",
                "chr",
                "client_data_tile",
                "close",
                "command",
                "cond",
                "cons",
                "cos",
                "cvunit",
                "defun",
                "defun-q",
                "defun-q-list-ref",
                "defun-q-list-set",
                "dictadd",
                "dictnext",
                "dictremove",
                "dictrename",
                "dictsearch",
                "dimx_tile",
                "dimy_tile",
                "distance",
                "distof",
                "done_dialog",
                "end_image",
                "end_list",
                "entdel",
                "entget",
                "entlast",
                "entmake",
                "entmakex",
                "entmod",
                "entnext",
                "entsel",
                "entupd",
                "eq",
                "equal",
                "*error*",
                "eval",
                "exit",
                "exp",
                "expand",
                "expt",
                "fill_image",
                "findfile",
                "fix",
                "float",
                "foreach",
                "function",
                "gc",
                "gcd",
                "get_attr",
                "get_tile",
                "getangle",
                "getcfg",
                "getcname",
                "getcorner",
                "getdist",
                "getenv",
                "getfiled",
                "getint",
                "getkword",
                "getorient",
                "getpoint",
                "getreal",
                "getstring",
                "getvar",
                "graphscr",
                "grclear",
                "grdraw",
                "grread",
                "grtext",
                "grvecs",
                "handent",
                "help",
                "if",
                "initcommandversion",
                "initdia",
                "initget",
                "inters",
                "itoa",
                "lambda",
                "last",
                "layoutlist",
                "layerstate-addlayers",
                "layerstate-compare",
                "layerstate-delete",
                "layerstate-export",
                "layerstate-getlastrestored",
                "layerstate-getlayers",
                "layerstate-getnames",
                "layerstate-has",
                "layerstate-import",
                "layerstate-importfromdb",
                "layerstate-removelayers",
                "layerstate-rename",
                "layerstate-restore",
                "layerstate-save",
                "length",
                "list",
                "listp",
                "load",
                "load_dialog",
                "log",
                "logand",
                "logior",
                "lsh",
                "mapcar",
                "max",
                "mem",
                "member",
                "menucmd",
                "menugroup",
                "min",
                "minusp",
                "mode_tile",
                "namedobjdict",
                "nentsel",
                "nentselp",
                "new_dialog",
                "not",
                "nth",
                "null",
                "numberp",
                "open",
                "or",
                "osnap",
                "polar",
                "prin1",
                "princ",
                "print",
                "progn",
                "prompt",
                "quit",
                "quote",
                "read",
                "read-char",
                "read-line",
                "redraw",
                "regapp",
                "rem",
                "repeat",
                "reverse",
                "rtos",
                "set",
                "set_tile",
                "setcfg",
                "setenv",
                "setfunhelp",
                "setq",
                "setvar",
                "setview",
                "sin",
                "slide_image",
                "snvalid",
                "sqrt",
                "ssadd",
                "ssdel",
                "ssget",
                "ssgetfirst",
                "sslength",
                "ssmemb",
                "ssname",
                "ssnamex",
                "sssetfirst",
                "startapp",
                "start_dialog",
                "start_image",
                "start_list",
                "strcase",
                "strcat",
                "strlen",
                "subst",
                "substr",
                "tablet",
                "tblnext",
                "tblobjname",
                "tblsearch",
                "term_dialog",
                "terpri",
                "textbox",
                "textpage",
                "textscr",
                "trace",
                "trans",
                "type",
                "unload_dialog",
                "untrace",
                "vector_image",
                "ver",
                "vl-acad-defun",
                "vl-acad-undefun",
                "vl-arx-import",
                "vl-bb-ref",
                "vl-bb-set",
                "vl-catch-all-apply",
                "vl-catch-all-error-message",
                "vl-catch-all-error-p",
                "vl-cmdf",
                "vl-consp",
                "vl-directory-files",
                "vl-doc-export",
                "vl-doc-import",
                "vl-doc-ref",
                "vl-doc-set",
                "vl-every",
                "vl-exit-with-error",
                "vl-exit-with-value",
                "vl-file-copy",
                "vl-file-delete",
                "vl-file-directory-p",
                "vl-file-rename",
                "vl-file-size",
                "vl-file-systime",
                "vl-filename-base",
                "vl-filename-directory",
                "vl-filename-extension",
                "vl-filename-mktemp",
                "vl-get-resource",
                "vl-list*",
                "vl-list->string",
                "vl-list-exported-functions",
                "vl-list-length",
                "vl-list-loaded-vlx",
                "vl-load-all",
                "vl-load-com",
                "vl-load-reactors",
                "vl-mkdir",
                "vl-member-if",
                "vl-member-if-not",
                "vl-position",
                "vl-prin1-to-string",
                "vl-princ-to-string",
                "vl-propagate",
                "vl-registry-delete",
                "vl-registry-descendents",
                "vl-registry-read",
                "vl-registry-write",
                "vl-remove",
                "vl-remove-if",
                "vl-remove-if-not",
                "vl-some",
                "vl-sort",
                "vl-sort-i",
                "vl-string->list",
                "vl-string-elt",
                "vl-string-left-trim",
                "vl-string-mismatch",
                "vl-string-position",
                "vl-string-right-trim",
                "vl-string-search",
                "vl-string-subst",
                "vl-string-translate",
                "vl-string-trim",
                "vl-symbol-name",
                "vl-symbol-value",
                "vl-symbolp",
                "vl-unload-vlx",
                "vl-vbaload",
                "vl-vbarun",
                "vl-vlx-loaded-p",
                "vlax-3D-point",
                "vlax-add-cmd",
                "vlax-create-object",
                "vlax-curve-getArea",
                "vlax-curve-getClosestPointTo",
                "vlax-curve-getClosestPointToProjection",
                "vlax-curve-getDistAtParam",
                "vlax-curve-getDistAtPoint",
                "vlax-curve-getEndParam",
                "vlax-curve-getEndPoint",
                "vlax-curve-getFirstDeriv",
                "vlax-curve-getParamAtDist",
                "vlax-curve-getParamAtPoint",
                "vlax-curve-getPointAtDist",
                "vlax-curve-getPointAtParam",
                "vlax-curve-getSecondDeriv",
                "vlax-curve-getStartParam",
                "vlax-curve-getStartPoint",
                "vlax-curve-isClosed",
                "vlax-curve-isPeriodic",
                "vlax-curve-isPlanar",
                "vlax-dump-object",
                "vlax-ename->vla-object",
                "vlax-erased-p",
                "vlax-for",
                "vlax-get-acad-object",
                "vlax-get-object",
                "vlax-get-or-create-object",
                "vlax-get-property",
                "vlax-import-type-library",
                "vlax-invoke-method",
                "vlax-ldata-delete",
                "vlax-ldata-get",
                "vlax-ldata-list",
                "vlax-ldata-put",
                "vlax-ldata-test",
                "vlax-make-safearray",
                "vlax-make-variant",
                "vlax-map-collection",
                "vlax-method-applicable-p",
                "vlax-object-released-p",
                "vlax-product-key",
                "vlax-property-available-p",
                "vlax-put-property",
                "vlax-read-enabled-p",
                "vlax-release-object",
                "vlax-remove-cmd",
                "vlax-safearray-fill",
                "vlax-safearray-get-dim",
                "vlax-safearray-get-element",
                "vlax-safearray-get-l-bound",
                "vlax-safearray-get-u-bound",
                "vlax-safearray-put-element",
                "vlax-safearray-type",
                "vlax-safearray->list",
                "vlax-tmatrix",
                "vlax-typeinfo-available-p",
                "vlax-variant-change-type",
                "vlax-variant-type",
                "vlax-variant-value",
                "vlax-vla-object->ename",
                "vlax-write-enabled-p",
                "vlisp-compile",
                "vlr-acdb-reactor",
                "vlr-add",
                "vlr-added-p",
                "vlr-beep-reaction",
                "vlr-command-reactor",
                "vlr-current-reaction-name",
                "vlr-data",
                "vlr-data-set",
                "vlr-deepclone-reactor",
                "vlr-docmanager-reactor",
                "vlr-dwg-reactor",
                "vlr-dxf-reactor",
                "vlr-editor-reactor",
                "vlr-insert-reactor",
                "vlr-linker-reactor",
                "vlr-lisp-reactor",
                "vlr-miscellaneous-reactor",
                "vlr-mouse-reactor",
                "vlr-notification",
                "vlr-object-reactor",
                "vlr-owner-add",
                "vlr-owner-remove",
                "vlr-owners",
                "vlr-pers",
                "vlr-pers-list",
                "vlr-pers-p",
                "vlr-pers-release",
                "vlr-reaction-name",
                "vlr-reaction-set",
                "vlr-reactions",
                "vlr-reactors",
                "vlr-remove",
                "vlr-remove-all",
                "vlr-set-notification",
                "vlr-sysvar-reactor",
                "vlr-toolbar-reactor",
                "vlr-trace-reaction",
                "vlr-type",
                "vlr-types",
                "vlr-undo-reactor",
                "vlr-wblock-reactor",
                "vlr-window-reactor",
                "vlr-xref-reactor",
                "vports",
                "wcmatch",
                "while",
                "write-char",
                "write-line",
                "xdroom",
                "xdsize",
                "zerop"
            };
#endregion
        }

        private static HashSet<string> _predefinedIdentifiers;

        public static bool IsPredefinedIdentifier(string identifier)
        {
            return _predefinedIdentifiers.Contains(identifier);
        }
    }

    public struct FilePosition
    {
        public static readonly FilePosition Empty = new FilePosition(0, 0);

        public int Line { get; set; }
        public int Column { get; set; }

        public FilePosition(int line, int column)
        {
            Line = line;
            Column = column;
        }

        public override string ToString()
        {
            return $"{Line}:{Column}";
        }

        public static FilePosition Parse(string s)
        {
            var pun = s.IndexOf(':');
            if (pun == -1)
                throw new FormatException("no : found");

            var fp = new FilePosition();
            fp.Line = int.Parse(s.Substring(0, pun));
            fp.Column = int.Parse(s.Substring(pun + 1));

            return fp;
        }
    }
}
